title: TypeBright
description: A website with a blog
footer_text: "Copyright 2021 Nicole Ann Carter "
header_feature_image: ../uploads/kelly-sikkema-hjdib8heptw-unsplash.jpg
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/screenshot-2021-09-28-at-14.24.16.png
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: false
upzoom: true
