title: TypeSmart
description: A website with a blog
footer_text: "Copyright 2021 Nicole Ann Carter "
header_feature_image: ../uploads/daniel-romero-73tftworkpg-unsplash.jpg
header_text: When typography speaks louder than words
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/untitled-15.png
favicon: ../uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
items: []
